### PR TITLE
bump widgets version for jlab 1.0

### PR DESCRIPTION
**Pull request by timkpaine**
Simple version bump 
Screen Shot 2019-09-06 at 10 42 07 AM

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @timkpaine. Does it break notebook support?

**Comment by timkpaine** [comment]
@Yomguithereal apologies for the delay, checking now

**Comment by timkpaine** [comment]
seems ok!
Screen Shot 2019-09-10 at 3 16 53 PM

**Comment by Yomguithereal** [comment]
@timkpaine v0.6.0 should be live now.

**Pull request merged**
