### PR TITLE
bump min widgets version for jlab2

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Hello @timkpaine. Isn't there a risk to break backwards compatibility for some people here? Will this still work with standard jupyter notebooks?

**Comment by timkpaine** [comment]
@Yomguithereal its v2 || v3, it only deals with compatibility with ipywidgets versions which are mostly on v3

**Comment by timkpaine** [comment]
but to answer the question, no, since its || it shouldn't break anything current

**Comment by Yomguithereal** [comment]
Let's try this then.

**Comment by Yomguithereal** [comment]
v0.6.1 should be live

**Pull request merged**
